#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
project_name_capitalcase=$(echo "$1" | awk -vFS="" -vOFS="" '{$1=toupper($1);print $0}')
project_name_lowercase=$(echo "$1" | awk '{print tolower($0)}')
project_description="$2"

function main() {
    initialize_folder_structure
    setup_new_project
}

function initialize_folder_structure() {
    cp -a ${SCRIPT_DIR}/template/ ${project_name_capitalcase}/
    cd ${project_name_capitalcase}

    mkdir -p src/main/resources
    mkdir -p src/test/resources
    mkdir -p src/main/java/org/bootcamp/${project_name_lowercase}
    mkdir -p src/test/java/org/bootcamp/${project_name_lowercase}
}

function setup_new_project() {
    setup_java_files
    replace_template_strings
    setup_and_prepare_git
}

function setup_java_files() {
    mv src/Template.class src/main/java/org/bootcamp/${project_name_lowercase}/${project_name_capitalcase}.java
    mv src/TemplateTest.class src/test/java/org/bootcamp/${project_name_lowercase}/${project_name_capitalcase}Test.java

    chmod +x gradlew
}

function replace_template_strings() {
    sed -i '' "s/template/$project_name_capitalcase/g" README.md
    sed -i '' "s/problem_statement/$project_description/g" README.md

    sed -i '' "s/template/$project_name_capitalcase/g" settings.gradle
    sed -i '' "s/template/$project_name_lowercase/g" build.gradle

    sed -i '' "s/template/$project_name_lowercase/g" src/main/java/org/bootcamp/${project_name_lowercase}/${project_name_capitalcase}.java
    sed -i '' "s/template/$project_name_lowercase/g" src/test/java/org/bootcamp/${project_name_lowercase}/${project_name_capitalcase}Test.java
    sed -i '' "s/Template/$project_name_capitalcase/g" src/main/java/org/bootcamp/${project_name_lowercase}/${project_name_capitalcase}.java
    sed -i '' "s/Template/$project_name_capitalcase/g" src/test/java/org/bootcamp/${project_name_lowercase}/${project_name_capitalcase}Test.java
}

function setup_and_prepare_git() {
    git init
    pre-commit install
    prepare_first_commit
}

function prepare_first_commit() {
    git add README.md
    git add .gitignore
    git add .pre-commit-config.yaml
    git add gradlew
    git add gradle/*
    git add build.gradle
    git add settings.gradle
}

main
