#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

the_description="$2"
lowercase=$(echo "$1" | awk '{print tolower($0)}')
uppercase="$1"

# copy the template and rename it
cp -a ${SCRIPT_DIR}/template/ ${uppercase}/
# go to the homework dir
cd ${uppercase}

# change access gradlew
chmod +x gradlew

# change 'template' to user input
sed -i '' "s/template/$uppercase/g" README.md settings.gradle
sed -i '' "s/template/$lowercase/g" build.gradle
# add simple problem statement
sed -i '' "s/problem_statement/$the_description/g" README.md

# initialize git
git init
# git commit
git add README.md .gitignore gradlew gradle/* build.gradle settings.gradle

# install pre-commit configuration
pre-commit install

# create resources directories
mkdir -p src/main/resources
mkdir -p src/test/resources

# create a directory for main and test
mkdir -p src/main/java/org/bootcamp/${lowercase}
mkdir -p src/test/java/org/bootcamp/${lowercase}

# move java files
mv src/Template.class src/main/java/org/bootcamp/${lowercase}/${uppercase}.java
mv src/TemplateTest.class src/test/java/org/bootcamp/${lowercase}/${uppercase}Test.java

# replace template to user input
sed -i '' "s/template/$lowercase/g" src/main/java/org/bootcamp/${lowercase}/${uppercase}.java
sed -i '' "s/template/$lowercase/g" src/test/java/org/bootcamp/${lowercase}/${uppercase}Test.java
sed -i '' "s/Template/$uppercase/g" src/main/java/org/bootcamp/${lowercase}/${uppercase}.java
sed -i '' "s/Template/$uppercase/g" src/test/java/org/bootcamp/${lowercase}/${uppercase}Test.java
sed -i '' "s/lowercase/$lowercase/g" src/main/java/org/bootcamp/${lowercase}/${uppercase}.java
sed -i '' "s/lowercase/$lowercase/g" src/test/java/org/bootcamp/${lowercase}/${uppercase}Test.java
